version: "3.8"
services:
  api:
    build: ./api
    # container_name: gif_editor-api_c
    ports:
      - '9000:9000'
  client:
    build: ./client
    # container_name: gif_editor-api_c
    depends_on:
      - api
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true